demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	# instance variable
  	@time = Time.now
  	# returns a list of all the files in the current directory
  	@files = Dir.glob('*')

  	
  end

  def goodbye
  end
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here</p>

<a href="/say/hello">Hello!</a>
<p>
	Say <%= link_to "Hello", say_hello_path %> again.
</p>

demo/app/views/say/hello.html.erb
<h1>Hello from Rails</h1>

<body>
	<p>It is now <%= @time %></p>
	<a href="/say/goodbye">Goodbye!</a>

	<p>
		Play time:
		<%= 1+2 %>
		<%= 'play' + 'time' %>
		<%= 1.hour.from_now.localtime %>
	</p>
	<p>
		Time to say
		<!-- link_to method -->
		<%= link_to "Goodbye", say_goodbye_path %>!
	</p>
	<!-- iterative do for instance variable @files -->
	<ul>
	<% @files.each do |file| %>
		<li>file name is: <%= file %></li>
	<% end %>
</ul>
</body>